from pathlib import Path
import tempfile

import networkx as nx
import pandas as pd
import streamlit as st
from pyvis.network import Network

st.set_page_config(layout="wide")
st.title("Face Similarity Network Dashboard")

# Prefer project output file generated by person_to_person_similarity.py
DEFAULT_DATA_PATH = Path("output/person_to_person_top_pairs.csv")

df = pd.read_csv(DEFAULT_DATA_PATH)
threshold = st.sidebar.slider("Minimum similarity", 0.0, 1.0, 0.5, 0.05)

# Build graph from person-pair similarity edges
G = nx.Graph()
for _, row in df.iterrows():
    try:
        G.add_edge(str(row["person_a"]), str(row["person_b"]), weight=float(row["similarity"]))
    except Exception:
        continue

if G.number_of_nodes() == 0:
    st.warning("No nodes found in graph from provided CSV.")
    st.stop()

node_list = sorted(G.nodes())
selected_node = st.sidebar.selectbox("Select a person", node_list)

filtered_edges = [(u, v, d) for u, v, d in G.edges(data=True) if d.get("weight", 0.0) >= threshold]
G_filtered = nx.Graph()
G_filtered.add_edges_from(filtered_edges)

if selected_node not in G_filtered:
    G_filtered.add_node(selected_node)

if G_filtered.degree(selected_node) > 0:
    ego = nx.ego_graph(G_filtered, selected_node)
else:
    ego = nx.Graph()
    ego.add_node(selected_node)

col1, col2, col3, col4, col5, col6 = st.columns([3, 2, 3, 1, 1, 1])

with col1:
    net = Network(height="700px", width="100%", bgcolor="#0d1117", font_color="white")

    for node in ego.nodes():
        degree = ego.degree(node)
        size = 10 + degree * 5
        color = "#FF4B4B" if node == selected_node else "#4FC3F7"
        net.add_node(node, label=node, size=size, color=color)

    for u, v, d in ego.edges(data=True):
        w = float(d.get("weight", 0.0))
        net.add_edge(u, v, value=w, width=max(1.0, w * 5.0))

    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".html")
    net.write_html(tmp_file.name)
    with open(tmp_file.name, "r", encoding="utf-8") as file:
        st.components.v1.html(file.read(), height=700)

with col2:
    st.subheader("Node Statistics")

    degree = G.degree(selected_node)
    neighbors = list(G.neighbors(selected_node))

    st.metric("Degree", degree)
    st.metric("Connections shown", max(0, len(ego.nodes()) - 1))

    st.subheader("Top Similar Connections")
    if neighbors:
        top_edges = sorted(
            [(n, float(G[selected_node][n]["weight"])) for n in neighbors],
            key=lambda x: x[1],
            reverse=True,
        )[:5]
        for node, score in top_edges:
            st.write(f"- {node}: {score:.3f}")
    else:
        st.write("No neighbors for selected node.")

with col3:
    st.subheader("Sorted Connectors")
    if neighbors:
        sorted_similar_node = sorted(
            [(n, float(G[selected_node][n]["weight"])) for n in neighbors],
            key=lambda x: x[1],
            reverse=True,
        )
        for node, weight in sorted_similar_node:
            st.write(f"{node} - {weight:.3f}")
    else:
        st.write("No connectors available.")

with col4:
    st.subheader("Similarity Extreme")
    if neighbors:
        max_similar_node = max(neighbors, key=lambda n: float(G[selected_node][n]["weight"]))
        min_similar_node = min(neighbors, key=lambda n: float(G[selected_node][n]["weight"]))
        max_similar = float(G[selected_node][max_similar_node]["weight"])
        min_similar = float(G[selected_node][min_similar_node]["weight"])
        st.write(f"Max: {max_similar_node} - {max_similar:.3f}")
        st.write(f"Min: {min_similar_node} - {min_similar:.3f}")
    else:
        st.write("No similarity extrema.")

with col5:
    st.subheader("Max Connector")
    max_connector_node = max(G.nodes(), key=lambda x: G.degree(x))
    max_connector = G.degree(max_connector_node)
    st.write(f"Node: {max_connector_node}")
    st.write(f"Degree: {max_connector}")

with col6:
    st.subheader("Min Connector")
    min_connector_node = min(G.nodes(), key=lambda x: G.degree(x))
    min_connector = G.degree(min_connector_node)
    st.write(f"Node: {min_connector_node}")
    st.write(f"Degree: {min_connector}")
